// <auto-generated>
// Gerado a partir de: interpretacao_solo_atualizada - Soja e Milho.xlsx (aba: CTC ≥ 8)
// Observação: Limites inclusivos exceto quando "<" ou ">" indicados na fonte.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace InterpretacaoSolo
{
    public enum Classe
    {
        MuitoBaixo,
        Baixo,
        Medio,
        Adequado,
        MuitoAlto
    }

    public readonly record struct Faixa(decimal? Min, decimal? Max, bool MinInclusivo, bool MaxInclusivo)
    {
        public bool Contem(decimal valor)
        {
            if (Min.HasValue)
            {
                var cmpMin = MinInclusivo ? valor >= Min.Value : valor > Min.Value;
                if (!cmpMin) return false;
            }
            if (Max.HasValue)
            {
                var cmpMax = MaxInclusivo ? valor <= Max.Value : valor < Max.Value;
                if (!cmpMax) return false;
            }
            return true;
        }
    }

    public enum AtributoSolo
    {
        [Description("pH (CaCl2)")]
        Ph,
        [Description("pH (H2O)")]
        Ph2,
        [Description("Cálcio - Ca (cmolc/dm³)")]
        CalcioCa,
        [Description("Magnésio - Mg (cmolc/dm³)")]
        MagnesioMg,
        [Description("Potássio - K (cmolc/dm³)")]
        PotassioK,
        [Description("Potássio - K (mg/dm³)")]
        PotassioK2,
        [Description("Saturação de base - SB (cmolc/dm³)")]
        SaturacaoDeBaseSb,
        [Description("Alumínio - Al (cmolc/dm³)")]
        AluminioAl,
        [Description("Acidez Potencial - H+Al (cmolc/dm³)")]
        AcidezPotencialHAl,
        [Description("Fósforo - P Mehlich-1 ( mg/dm³)")]
        FosforoPMehlich1,
        [Description("Fósforo - P Resina ( mg/dm³)")]
        FosforoPResina,
        [Description("Matéria Orgânica - MO (g/dm³)")]
        MateriaOrganicaMo,
        [Description("Carbono organico - C-org (g/dm³)")]
        CarbonoOrganicoCOrg,
        [Description("CTC efetiva (t)")]
        CtcEfetiva,
        [Description("CTC a pH 7 (T)")]
        CtcAPh7,
        [Description("saturação por bases  - V%")]
        SaturacaoPorBasesV,
        [Description("saturação por Alumínio - m% (Al)")]
        SaturacaoPorAluminioM,
        [Description("Participação de Ca/CTC (%)")]
        ParticipacaoDeCaCtc,
        [Description("Participação de Mg/CTC (%)")]
        ParticipacaoDeMgCtc,
        [Description("Participação de K/CTC (%)")]
        ParticipacaoDeKCtc,
        [Description("Participação de H+Al/CTC (%)")]
        ParticipacaoDeHAlCtc,
        [Description("Participação de Al/CTC (%)")]
        ParticipacaoDeAlCtc,
        [Description("Relação de Ca/Mg")]
        RelacaoDeCaMg,
        [Description("Relação de Ca/K")]
        RelacaoDeCaK,
        [Description("Relação de Mg/K")]
        RelacaoDeMgK,
        [Description("Boro - B (mg/dm³)")]
        BoroB,
        [Description("Cobre - Cu (mg/dm³)")]
        CobreCu,
        [Description("Zinco - Zn (mg/dm³)")]
        ZincoZn,
        [Description("ManganêS - Mn (mg/dm³)")]
        ManganesMn,
        [Description("Ferro - Fe (mg/dm³)")]
        FerroFe,
        [Description("Carbono - C")]
        CarbonoC,
        [Description("Enxofre - S")]
        EnxofreS,
        [Description("Argila (g/Kg)")]
        Argila,
    }

    public static class EnumExtensoes
    {
        public static string Descricao(this Enum valor)
        {
            var campo = valor.GetType().GetField(valor.ToString());
            if (campo == null) return valor.ToString();
            var attr = (DescriptionAttribute?)Attribute.GetCustomAttribute(campo, typeof(DescriptionAttribute));
            return attr?.Description ?? valor.ToString();
        }
    }

    public sealed class FaixasDoAtributo
    {
        public required AtributoSolo Atributo { get; init; }
        public required Dictionary<Classe, Faixa> Faixas { get; init; }
        public Classe? Classificar(decimal valor)
        {
            foreach (var kv in Faixas)
            {
                if (kv.Value.Contem(valor)) return kv.Key;
            }
            return null;
        }
    }

    public static class FaixasSoloCtcMaiorOuIgual8
    {
        public static readonly IReadOnlyList<FaixasDoAtributo> Todas = new List<FaixasDoAtributo>
        {
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.Ph,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 4.5m, false, false),
                    [Classe.Baixo] = new Faixa(4.5m, 4.9m, true, true),
                    [Classe.Medio] = new Faixa(5m, 5.4m, true, true),
                    [Classe.Adequado] = new Faixa(5.5m, 6m, true, true),
                    [Classe.MuitoAlto] = new Faixa(6m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.Ph2,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 5.2m, false, false),
                    [Classe.Baixo] = new Faixa(5.2m, 5.6m, true, true),
                    [Classe.Medio] = new Faixa(5.7m, 6.1m, true, true),
                    [Classe.Adequado] = new Faixa(6.2m, 6.8m, true, true),
                    [Classe.MuitoAlto] = new Faixa(6.8m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.CalcioCa,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 1.5m, false, false),
                    [Classe.Baixo] = new Faixa(1.5m, 2m, true, true),
                    [Classe.Medio] = new Faixa(2m, 3.6m, true, true),
                    [Classe.Adequado] = new Faixa(3.6m, 6m, true, true),
                    [Classe.MuitoAlto] = new Faixa(6m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.MagnesioMg,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 0.3m, false, false),
                    [Classe.Baixo] = new Faixa(0.3m, 0.5m, true, true),
                    [Classe.Medio] = new Faixa(0.6m, 1m, true, true),
                    [Classe.Adequado] = new Faixa(1.1m, 2m, true, true),
                    [Classe.MuitoAlto] = new Faixa(2m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.PotassioK,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 0.07m, false, false),
                    [Classe.Baixo] = new Faixa(0.07m, 0.1m, true, true),
                    [Classe.Medio] = new Faixa(0.11m, 0.2m, true, true),
                    [Classe.Adequado] = new Faixa(0.21m, 0.3m, true, true),
                    [Classe.MuitoAlto] = new Faixa(0.3m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.PotassioK2,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 27m, false, false),
                    [Classe.Baixo] = new Faixa(27m, 39m, true, true),
                    [Classe.Medio] = new Faixa(40m, 78m, true, true),
                    [Classe.Adequado] = new Faixa(79m, 117m, true, true),
                    [Classe.MuitoAlto] = new Faixa(117m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.SaturacaoDeBaseSb,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 2m, false, false),
                    [Classe.Baixo] = new Faixa(2m, 4m, true, true),
                    [Classe.Medio] = new Faixa(4m, 6m, true, true),
                    [Classe.Adequado] = new Faixa(6m, 12m, true, true),
                    [Classe.MuitoAlto] = new Faixa(12m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.AluminioAl,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(1m, null, false, false),
                    [Classe.Baixo] = new Faixa(0.6m, 1m, true, true),
                    [Classe.Medio] = new Faixa(0.3m, 0.5m, true, true),
                    [Classe.Adequado] = new Faixa(0.1m, 0.2m, true, true),
                    [Classe.MuitoAlto] = new Faixa(null, 0.1m, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.AcidezPotencialHAl,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(10m, null, false, false),
                    [Classe.Baixo] = new Faixa(8m, 10m, true, true),
                    [Classe.Medio] = new Faixa(6m, 7.9m, true, true),
                    [Classe.Adequado] = new Faixa(3m, 5.9m, true, true),
                    [Classe.MuitoAlto] = new Faixa(null, 3m, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.FosforoPMehlich1,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 6m, false, false),
                    [Classe.Baixo] = new Faixa(6m, 12m, true, true),
                    [Classe.Medio] = new Faixa(13m, 18m, true, true),
                    [Classe.Adequado] = new Faixa(19m, 25m, true, true),
                    [Classe.MuitoAlto] = new Faixa(25m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.FosforoPResina,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 12m, false, false),
                    [Classe.Baixo] = new Faixa(12m, 20m, true, true),
                    [Classe.Medio] = new Faixa(21m, 30m, true, true),
                    [Classe.Adequado] = new Faixa(31m, 45m, true, true),
                    [Classe.MuitoAlto] = new Faixa(45m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.MateriaOrganicaMo,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 15m, false, false),
                    [Classe.Baixo] = new Faixa(15m, 25m, true, true),
                    [Classe.Medio] = new Faixa(26m, 35m, true, true),
                    [Classe.Adequado] = new Faixa(36m, 50m, true, true),
                    [Classe.MuitoAlto] = new Faixa(50m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.CarbonoOrganicoCOrg,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 8.7m, false, false),
                    [Classe.Baixo] = new Faixa(8.7m, 14.5m, true, true),
                    [Classe.Medio] = new Faixa(14.6m, 20.3m, true, true),
                    [Classe.Adequado] = new Faixa(20.4m, 29m, true, true),
                    [Classe.MuitoAlto] = new Faixa(29m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.CtcEfetiva,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 2m, false, false),
                    [Classe.Baixo] = new Faixa(2m, 4m, true, true),
                    [Classe.Medio] = new Faixa(4m, 6m, true, true),
                    [Classe.Adequado] = new Faixa(6m, 12m, true, true),
                    [Classe.MuitoAlto] = new Faixa(12m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.CtcAPh7,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 4m, false, false),
                    [Classe.Baixo] = new Faixa(4m, 8m, true, true),
                    [Classe.Medio] = new Faixa(8m, 12m, true, true),
                    [Classe.Adequado] = new Faixa(12m, 20m, true, true),
                    [Classe.MuitoAlto] = new Faixa(20m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.SaturacaoPorBasesV,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 45m, false, false),
                    [Classe.Baixo] = new Faixa(45m, 50m, true, true),
                    [Classe.Medio] = new Faixa(51m, 65m, true, true),
                    [Classe.Adequado] = new Faixa(66m, 75m, true, true),
                    [Classe.MuitoAlto] = new Faixa(75m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.SaturacaoPorAluminioM,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(40m, null, false, false),
                    [Classe.Baixo] = new Faixa(21m, 40m, true, true),
                    [Classe.Medio] = new Faixa(11m, 20m, true, true),
                    [Classe.Adequado] = new Faixa(6m, 10m, true, true),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.ParticipacaoDeCaCtc,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 30m, false, false),
                    [Classe.Baixo] = new Faixa(30m, 40m, true, true),
                    [Classe.Medio] = new Faixa(41m, 50m, true, true),
                    [Classe.Adequado] = new Faixa(51m, 70m, true, true),
                    [Classe.MuitoAlto] = new Faixa(70m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.ParticipacaoDeMgCtc,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 8m, false, false),
                    [Classe.Baixo] = new Faixa(8m, 10m, true, true),
                    [Classe.Medio] = new Faixa(11m, 15m, true, true),
                    [Classe.Adequado] = new Faixa(16m, 20m, true, true),
                    [Classe.MuitoAlto] = new Faixa(20m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.ParticipacaoDeKCtc,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 2m, false, false),
                    [Classe.Baixo] = new Faixa(2m, 3m, true, true),
                    [Classe.Medio] = new Faixa(3m, 4m, true, true),
                    [Classe.Adequado] = new Faixa(4m, 5m, true, true),
                    [Classe.MuitoAlto] = new Faixa(5m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.ParticipacaoDeHAlCtc,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(50m, null, false, false),
                    [Classe.Baixo] = new Faixa(40m, 50m, true, true),
                    [Classe.Medio] = new Faixa(40m, 30m, true, true),
                    [Classe.Adequado] = new Faixa(30m, 20m, true, true),
                    [Classe.MuitoAlto] = new Faixa(null, 20m, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.ParticipacaoDeAlCtc,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(20m, null, false, false),
                    [Classe.Baixo] = new Faixa(15m, 20m, true, true),
                    [Classe.Medio] = new Faixa(10m, 14m, true, true),
                    [Classe.Adequado] = new Faixa(5m, 9m, true, true),
                    [Classe.MuitoAlto] = new Faixa(null, 5m, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.RelacaoDeCaMg,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 2m, false, false),
                    [Classe.Baixo] = new Faixa(2m, 3m, true, true),
                    [Classe.Medio] = new Faixa(3m, 4m, true, true),
                    [Classe.Adequado] = new Faixa(4m, 6m, true, true),
                    [Classe.MuitoAlto] = new Faixa(6m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.RelacaoDeCaK,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 8m, false, false),
                    [Classe.Baixo] = new Faixa(8m, 15m, true, true),
                    [Classe.Medio] = new Faixa(16m, 20m, true, true),
                    [Classe.Adequado] = new Faixa(21m, 30m, true, true),
                    [Classe.MuitoAlto] = new Faixa(30m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.RelacaoDeMgK,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 2m, false, false),
                    [Classe.Baixo] = new Faixa(2m, 4m, true, true),
                    [Classe.Medio] = new Faixa(5m, 8m, true, true),
                    [Classe.Adequado] = new Faixa(9m, 15m, true, true),
                    [Classe.MuitoAlto] = new Faixa(15m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.BoroB,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 0.25m, false, false),
                    [Classe.Baixo] = new Faixa(0.26m, 0.4m, true, true),
                    [Classe.Medio] = new Faixa(0.41m, 0.6m, true, true),
                    [Classe.Adequado] = new Faixa(0.6m, 0.8m, true, true),
                    [Classe.MuitoAlto] = new Faixa(0.8m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.CobreCu,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 0.2m, false, false),
                    [Classe.Baixo] = new Faixa(0.2m, 0.3m, true, true),
                    [Classe.Medio] = new Faixa(0.31m, 0.5m, true, true),
                    [Classe.Adequado] = new Faixa(0.5m, 1m, true, true),
                    [Classe.MuitoAlto] = new Faixa(1m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.ZincoZn,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 0.6m, false, false),
                    [Classe.Baixo] = new Faixa(0.6m, 0.8m, true, true),
                    [Classe.Medio] = new Faixa(0.81m, 1.2m, true, true),
                    [Classe.Adequado] = new Faixa(1.21m, 5m, true, true),
                    [Classe.MuitoAlto] = new Faixa(5m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.ManganesMn,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 1m, false, false),
                    [Classe.Baixo] = new Faixa(1m, 2m, true, true),
                    [Classe.Medio] = new Faixa(2.1m, 5m, true, true),
                    [Classe.Adequado] = new Faixa(5.1m, 20m, true, true),
                    [Classe.MuitoAlto] = new Faixa(20m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.FerroFe,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 2.5m, false, false),
                    [Classe.Baixo] = new Faixa(2.5m, 5m, true, true),
                    [Classe.Medio] = new Faixa(5.1m, 10m, true, true),
                    [Classe.Adequado] = new Faixa(11m, 30m, true, true),
                    [Classe.MuitoAlto] = new Faixa(30m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.CarbonoC,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 10m, false, false),
                    [Classe.Baixo] = new Faixa(10m, 20m, true, true),
                    [Classe.Medio] = new Faixa(20m, 30m, true, true),
                    [Classe.Adequado] = new Faixa(30m, 40m, true, true),
                    [Classe.MuitoAlto] = new Faixa(40m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.EnxofreS,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 5m, false, false),
                    [Classe.Baixo] = new Faixa(5m, 10m, true, true),
                    [Classe.Medio] = new Faixa(10m, 15m, true, true),
                    [Classe.Adequado] = new Faixa(15m, 20m, true, true),
                    [Classe.MuitoAlto] = new Faixa(20m, null, false, false),
                }
            },
            new FaixasDoAtributo
            {
                Atributo = AtributoSolo.Argila,
                Faixas = new Dictionary<Classe, Faixa>
                {
                    [Classe.MuitoBaixo] = new Faixa(null, 150m, false, false),
                    [Classe.Baixo] = new Faixa(150m, 350m, true, true),
                    [Classe.Medio] = new Faixa(350m, 600m, true, true),
                    [Classe.Adequado] = new Faixa(600m, 1000m, true, true),
                    [Classe.MuitoAlto] = new Faixa(1000m, null, false, false),
                }
            },
        };

        public static FaixasDoAtributo? Obter(AtributoSolo atributo) =>
            Todas.FirstOrDefault(a => a.Atributo == atributo);
    }
}
